// Auto-generated by build-vercel.sh - do not edit
import type { Product } from "./products";
export const products: Product[] = [
  {
    "id": "desk-mat-premium",
    "name": "FeltSpace Premium Desk Mat",
    "slug": "feltspace-premium-desk-mat",
    "category": "accessories",
    "price": 39.99,
    "cost": 13,
    "description": "A desk mat that transforms your workspace. Made from 100% merino wool felt with a suede leather underside, the FeltSpace Desk Mat provides a luxurious surface for typing and writing. Water-resistant and easy to clean.",
    "features": [
      "100% merino wool felt surface",
      "Genuine suede leather underside",
      "Water-resistant coating",
      "31.5\" x 15.7\" (large size)",
      "Anti-fray stitched edges"
    ],
    "images": [
      "https://picsum.photos/seed/mat/600/600",
      "https://picsum.photos/seed/mat2/600/600"
    ],
    "rating": 4.9,
    "reviews": 203,
    "inStock": true,
    "stripePaymentLink": "https://buy.stripe.com/aFa8wPeWbatU5fTc19fnO00"
  },
  {
    "id": "noise-cancelling-panels",
    "name": "FocusZone Acoustic Desk Panels",
    "slug": "focuszone-acoustic-desk-panels",
    "category": "accessories",
    "price": 49.99,
    "cost": 18,
    "description": "Create a quiet zone anywhere. FocusZone Acoustic Panels attach to the sides and back of your desk, absorbing ambient noise and reducing echo. The hexagonal design looks stunning and doubles as a pinboard. Each set includes 6 panels with mounting hardware.",
    "features": [
      "6 hexagonal acoustic panels",
      "Noise reduction coefficient: 0.85",
      "Doubles as a pinboard",
      "Includes mounting hardware",
      "Available in 4 colors"
    ],
    "images": [
      "https://picsum.photos/seed/panels/600/600",
      "https://picsum.photos/seed/panels2/600/600"
    ],
    "rating": 4.6,
    "reviews": 117,
    "inStock": true,
    "stripePaymentLink": "https://buy.stripe.com/00wfZh01hdG60ZD5CLfnO01"
  },
  {
    "id": "magnetic-cable-clips",
    "name": "Magnetic Cable Clips (6-Pack)",
    "slug": "magnetic-cable-clips-6-pack",
    "category": "cable-management",
    "price": 9,
    "cost": 3,
    "description": "The fastest way to a clean desk. These ultra-strong magnetic cable clips snap onto any ferrous surface or stick anywhere with the included adhesive metal plates. Route charging cables, headphone cords, and USB cables neatly along your desk edge. Each clip holds up to 3 cables. No tools, no permanent mounting.",
    "features": [
      "Material: Neodymium magnet + silicone grip",
      "Pack Size: 6 clips + 6 adhesive metal plates",
      "Capacity: 3 cables per clip",
      "Color: Black"
    ],
    "images": [
      "/images/magnetic-cable-clips.jpg"
    ],
    "rating": 4.3,
    "reviews": 93,
    "inStock": true,
    "stripePaymentLink": "https://buy.stripe.com/bJe8wP8xN45w6jX3uDfnO02"
  },
  {
    "id": "cable-management-sleeve",
    "name": "Braided Cable Management Sleeve",
    "slug": "braided-cable-management-sleeve",
    "category": "cable-management",
    "price": 14,
    "cost": 5,
    "description": "Tame the snake pit of cords under your desk in seconds. This expandable braided sleeve wraps 3-8 cables into one tidy bundle. Simply gather your cables, thread them through, and zip it closed. The adjustable length (cut to fit) and velour interior protect cables from wear. Includes 4 cable clips for desk-edge routing.",
    "features": [
      "Material: Braided nylon + velour lining",
      "Length: 20 inches (cuttable)",
      "Capacity: 3-8 cables",
      "Includes: 1 sleeve + 4 adhesive cable clips"
    ],
    "images": [
      "/images/cable-management-sleeve.jpg"
    ],
    "rating": 4.4,
    "reviews": 142,
    "inStock": true,
    "stripePaymentLink": "https://buy.stripe.com/14A4gz15l8lMbEh8OXfnO03"
  },
  {
    "id": "mesh-desk-organizer",
    "name": "Mesh Desk Organizer Caddy",
    "slug": "mesh-desk-organizer-caddy",
    "category": "desk-organization",
    "price": 17,
    "cost": 6,
    "description": "Stop digging through piles of papers and accessories. This modular mesh organizer keeps everything in its place with 5 compartments sized for pens, phone, sticky notes, paper clips, and more. The minimalist metal design complements any desk aesthetic. Slide a photo or to-do card in the front slot for easy visibility.",
    "features": [
      "Material: Powder-coated steel mesh",
      "Dimensions: 8.5 x 5 x 4.5 inches",
      "Compartments: 5 compartments + front card slot",
      "Color: Black / White"
    ],
    "images": [
      "/images/mesh-desk-organizer.jpg"
    ],
    "rating": 4.2,
    "reviews": 45,
    "inStock": true,
    "stripePaymentLink": "https://buy.stripe.com/28E6oHaFVdG6cIl0irfnO04"
  },
  {
    "id": "under-desk-drawer",
    "name": "Under Desk Drawer Organizer",
    "slug": "under-desk-drawer-organizer",
    "category": "desk-organization",
    "price": 29,
    "cost": 11,
    "description": "Instantly reclaim your desktop space with this sleek under-desk drawer. Mounts underneath any desk surface in seconds (no tools required) to keep pens, sticky notes, chargers, and small accessories organized and out of sight. The smooth ball-bearing glides make access effortless. Available in bamboo and black finishes.",
    "features": [
      "Material: Bamboo / ABS plastic",
      "Dimensions: 16 x 8 x 2.5 inches",
      "Installation: Adhesive tape or screws (both included)",
      "Weight Capacity: 5 lbs"
    ],
    "images": [
      "/images/under-desk-drawer.jpg"
    ],
    "rating": 4.5,
    "reviews": 78,
    "inStock": true,
    "stripePaymentLink": "https://buy.stripe.com/8x27sLaFV1XofUx3uDfnO05"
  },
  {
    "id": "bamboo-monitor-stand",
    "name": "Bamboo Monitor Stand with Storage",
    "slug": "bamboo-monitor-stand-with-storage",
    "category": "desk-organization",
    "price": 35,
    "cost": 14,
    "description": "A beautiful workspace starts at eye level. This premium bamboo monitor stand raises your screen 4 inches for optimal viewing posture while adding valuable storage underneath. The built-in drawer keeps pens, keys, and gadgets tucked away. The sturdy base holds monitors up to 35 lbs. Also compatible with laptops.",
    "features": [
      "Material: Natural bamboo",
      "Dimensions: 17.5 x 9.5 x 4 inches",
      "Drawer: Built-in sliding drawer",
      "Weight Capacity: 35 lbs"
    ],
    "images": [
      "/images/bamboo-monitor-stand.jpg"
    ],
    "rating": 4.6,
    "reviews": 273,
    "inStock": true,
    "stripePaymentLink": "https://buy.stripe.com/8x228r5lBatU37LaX5fnO06"
  },
  {
    "id": "ergo-gel-wrist-rest",
    "name": "Ergonomic Gel Wrist Rest",
    "slug": "ergonomic-gel-wrist-rest",
    "category": "ergonomics",
    "price": 22,
    "cost": 8,
    "description": "Experience all-day comfort with our premium Ergonomic Gel Wrist Rest. The gel-infused memory foam conforms to your wrists, reducing pressure points and preventing repetitive strain during long work sessions. The non-slip rubber base keeps it firmly in place whether you're typing or mousing. Available in full-size keyboard and compact versions.",
    "features": [
      "Material: Gel-infused memory foam + rubber base",
      "Dimensions: 18 x 3.5 x 0.8 inches",
      "Color: Black / Gray",
      "Compatibility: Full-size and TKL keyboards"
    ],
    "images": [
      "/images/ergo-gel-wrist-rest.jpg"
    ],
    "rating": 4.3,
    "reviews": 89,
    "inStock": true,
    "stripePaymentLink": "https://buy.stripe.com/cNi14n5lBdG67o10irfnO07"
  },
  {
    "id": "memory-foam-seat-cushion",
    "name": "Memory Foam Coccyx Seat Cushion",
    "slug": "memory-foam-coccyx-seat-cushion",
    "category": "ergonomics",
    "price": 27,
    "cost": 10,
    "description": "Transform any chair into an ergonomic throne. The contoured memory foam design relieves tailbone pressure, promotes proper spinal alignment, and reduces hip strain during 8-hour desk marathons. Features a breathable velvet cover with a non-slip bottom and a built-in carrying handle for easy transport.",
    "features": [
      "Material: High-density memory foam + velvet cover",
      "Dimensions: 17 x 14 x 3.5 inches",
      "Cover: Removable and washable",
      "Weight Capacity: Up to 300 lbs"
    ],
    "images": [
      "/images/memory-foam-seat-cushion.jpg"
    ],
    "rating": 4.4,
    "reviews": 112,
    "inStock": true,
    "stripePaymentLink": "https://buy.stripe.com/6oU28reWbatU0ZD2qzfnO08"
  },
  {
    "id": "adjustable-laptop-stand",
    "name": "Adjustable Aluminum Laptop Stand",
    "slug": "adjustable-aluminum-laptop-stand",
    "category": "ergonomics",
    "price": 39,
    "cost": 15,
    "description": "Raise your laptop screen to eye level and say goodbye to neck strain. This ultra-portable aluminum stand features 6 adjustable height angles, a ventilated honeycomb design for heat dissipation, and a fold-flat form factor that slips into any bag. Holds laptops from 10 to 17 inches with a secure rubber grip.",
    "features": [
      "Material: Aerospace-grade aluminum",
      "Weight: 0.8 lbs",
      "Height Settings: 6 angles (1.2 to 5.9 inches)",
      "Compatibility: 10-17 inch laptops"
    ],
    "images": [
      "/images/adjustable-laptop-stand.jpg"
    ],
    "rating": 4.7,
    "reviews": 156,
    "inStock": true,
    "stripePaymentLink": "https://buy.stripe.com/bJe4gzaFV59AbEh6GPfnO09"
  },
  {
    "id": "desk-organizer-set",
    "name": "ZenDesk Organizer Set",
    "slug": "zendesk-organizer-set",
    "category": "organization",
    "price": 34.99,
    "cost": 11,
    "description": "Declutter your desk, declutter your mind. The ZenDesk Organizer Set includes a multi-compartment pen holder, a floating phone stand, a sticky-note dispenser, and a minimalist tray for small accessories. All pieces are made from matte-finish ABS plastic with non-slip bases.",
    "features": [
      "4-piece desk organization system",
      "Matte ABS construction with non-slip bases",
      "Floating phone stand fits all phones",
      "Modular — arrange to suit your space",
      "Easy to clean"
    ],
    "images": [
      "https://picsum.photos/seed/organizer/600/600",
      "https://picsum.photos/seed/organizer2/600/600"
    ],
    "rating": 4.4,
    "reviews": 142,
    "inStock": true,
    "stripePaymentLink": "https://buy.stripe.com/4gM7sLg0f6dEgYBd5dfnO0a"
  },
  {
    "id": "whiteboard-wall-calendar",
    "name": "Reusable Whiteboard Wall Calendar",
    "slug": "reusable-whiteboard-wall-calendar",
    "category": "productivity",
    "price": 21,
    "cost": 8,
    "description": "Never lose track of deadlines again. This large adhesive-backed whiteboard calendar sticks to any smooth wall without nails or tape and removes cleanly without residue. The 12-month grid layout gives you a bird's-eye view of your entire year. Writes clean with dry-erase markers and wipes effortlessly. Includes 3 markers and a microfiber cloth.",
    "features": [
      "Material: PET film + adhesive backing",
      "Dimensions: 36 x 24 inches",
      "Grid: 12 months visible at once",
      "Includes: 3 dry-erase markers + microfiber cloth",
      "Installation: Peel-and-stick, removable without residue"
    ],
    "images": [
      "/images/whiteboard-wall-calendar.jpg"
    ],
    "rating": 4.2,
    "reviews": 56,
    "inStock": true,
    "stripePaymentLink": "https://buy.stripe.com/14A3cv5lB59A6jXaX5fnO0b"
  },
  {
    "id": "focus-timer-cube",
    "name": "Bluetooth Focus Timer Cube",
    "slug": "bluetooth-focus-timer-cube",
    "category": "productivity",
    "price": 27,
    "cost": 10,
    "description": "Finally, a focus timer you can actually feel. This tactile Bluetooth cube lets you set Pomodoro sessions with a simple flip — rotate to the desired time (5, 15, 25, or 45 minutes) and it starts counting down with a gentle vibration when time's up. Syncs wirelessly to display your focus stats on desktop or phone. No screens, no distractions — just focused work.",
    "features": [
      "Material: Silicone + recycled ABS",
      "Timer Settings: 5 / 15 / 25 / 45 minutes",
      "Connectivity: Bluetooth 5.0 (syncs with iOS/Android/Desktop)",
      "Battery: Built-in rechargeable (3 weeks per charge)",
      "Notification: Silent vibration + LED glow"
    ],
    "images": [
      "/images/focus-timer-cube.jpg"
    ],
    "rating": 4.5,
    "reviews": 118,
    "inStock": true,
    "stripePaymentLink": "https://buy.stripe.com/4gM4gz15l8lMeQt8OXfnO0c"
  },
  {
    "id": "rgb-strip-lights",
    "name": "RGB Smart LED Strip Lights",
    "slug": "rgb-smart-led-strip-lights",
    "category": "smart-lighting",
    "price": 19,
    "cost": 7,
    "description": "Transform your workspace with 16 million colors. These smart LED strips sync to your music, games, or productivity rhythm via the free app. Includes adhesive backing for easy setup under desks, behind monitors, or along shelving. Features voice control (Alexa/Google), timer scheduling, and scene presets.",
    "features": [
      "Length: 16.4 ft (5m)",
      "Control: App + Voice (Alexa/Google)",
      "LED Count: 60 LEDs per meter",
      "Power: USB powered",
      "Features: Music sync, timer, 16 million colors"
    ],
    "images": [
      "/images/rgb-strip-lights.jpg"
    ],
    "rating": 4.1,
    "reviews": 67,
    "inStock": true,
    "stripePaymentLink": "https://buy.stripe.com/cNi7sL6pF45w8s5c19fnO0d"
  },
  {
    "id": "monitor-light-bar",
    "name": "Monitor Light Bar",
    "slug": "monitor-light-bar",
    "category": "smart-lighting",
    "price": 39,
    "cost": 16,
    "description": "Light your desk without lighting your screen. The asymmetric optical design of this monitor light bar illuminates your workspace while preventing screen glare — perfect for dim offices and late-night work sessions. Features auto-dimming ambient sensor, touch control, and a no-screw clamp that fits any monitor. USB powered.",
    "features": [
      "Material: Aluminum alloy",
      "Light Modes: Auto-dimming + 3 brightness levels, 3 color temps",
      "Clamp Range: Up to 1.2 inches thick",
      "Power: USB-C (adapter included)",
      "Color Rendering: Ra > 95"
    ],
    "images": [
      "/images/monitor-light-bar.jpg"
    ],
    "rating": 4.6,
    "reviews": 203,
    "inStock": true,
    "stripePaymentLink": "https://buy.stripe.com/aFa00j7tJeKagYBfdlfnO0e"
  },
  {
    "id": "led-desk-lamp-charger",
    "name": "LED Desk Lamp with Wireless Charger",
    "slug": "led-desk-lamp-with-wireless-charger",
    "category": "smart-lighting",
    "price": 45,
    "cost": 18,
    "description": "Light up your workspace and charge your devices simultaneously. This sleek LED desk lamp features 5 brightness levels, 3 color temperatures (warm, natural, cool), and a built-in Qi wireless charging pad at the base. The flexible gooseneck arm directs light exactly where you need it. USB-A port charges a second device.",
    "features": [
      "Material: Aluminum + ABS",
      "Light Modes: 5 brightness x 3 color temperatures",
      "Charging: 15W Qi wireless + USB-A port",
      "Power: USB-C powered (adapter included)"
    ],
    "images": [
      "/images/led-desk-lamp-charger.jpg"
    ],
    "rating": 4.8,
    "reviews": 451,
    "inStock": true,
    "stripePaymentLink": "https://buy.stripe.com/7sYfZhg0f7hI5fTghpfnO0f"
  }
];
