#!/usr/bin/env bash
# Produce a Vercel Build Output API bundle (.vercel/output) for this site, then
# deploy it with:  bunx vercel deploy --prebuilt
#
# Why Build Output API instead of Vercel's Vite/framework detection:
#  - TanStack Start emits a host-agnostic fetch handler (dist/server/server.js)
#    that dynamic-imports its own ./assets chunks and externalizes node deps.
#    Letting Vercel trace/detect that is fragile.
#  - Bundling it into one self-contained file (deps + dynamic chunks inlined) in a
#    single render.func removes all tracing/detection risk. vercel-entry.ts adapts
#    the Node (req,res) launcher to the web fetch handler.
set -euo pipefail
cd "$(dirname "$0")"
umask 002

echo "[1/3] vite build (light — safe under the sandbox memory cap)"
# Generate embedded products data so no file reading is needed at runtime on Vercel
node -e "
const fs = require('fs');
const data = JSON.parse(fs.readFileSync('products.json', 'utf8'));
fs.writeFileSync('src/lib/products-data.ts',
  '// Auto-generated by build-vercel.sh - do not edit\n' +
  'import type { Product } from \"./products\";\n' +
  'export const products: Product[] = ' + JSON.stringify(data, null, 2) + ';\n'
);
"
# The workspace starts as sources only (deps live with the image's pre-built
# placeholder copy); no-op once node_modules is current.
# Use npm instead of bun to avoid bun's global cache permissions issue
BUN_INSTALL="${BUN_INSTALL:-/tmp/bun-$(id -un)}"
mkdir -p "$BUN_INSTALL"
npm install --no-audit --no-fund 2>/dev/null || true
npx vite build

echo "[2/3] assemble .vercel/output (Build Output API v3)"
rm -rf .vercel/output
mkdir -p .vercel/output/functions/render.func
cp -R dist/client .vercel/output/static
rm -f .vercel/output/static/index.html   # SSR owns "/", not a static shell

# Generate sitemap.xml from products.json
node -e "
const fs = require('fs');
const products = JSON.parse(fs.readFileSync('products.json', 'utf8'));
const BASE = 'https://flowcart-cyan.vercel.app';
const urls = [
  { loc: BASE, priority: '1.0', changefreq: 'daily' },
  { loc: BASE + '/products', priority: '0.9', changefreq: 'daily' },
  { loc: BASE + '/blog', priority: '0.8', changefreq: 'weekly' },
  { loc: BASE + '/cart', priority: '0.5', changefreq: 'weekly' },
  ...products.map(p => ({ loc: BASE + '/products/' + p.slug, priority: '0.7', changefreq: 'weekly' })),
];
const xml = '<?xml version=\"1.0\" encoding=\"UTF-8\"?>\\n<urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\">\\n' +
  urls.map(u => '  <url>\\n    <loc>' + u.loc + '</loc>\\n    <priority>' + u.priority + '</priority>\\n    <changefreq>' + u.changefreq + '</changefreq>\\n  </url>').join('\\n') +
  '\\n</urlset>';
fs.writeFileSync('.vercel/output/static/sitemap.xml', xml);
"

echo "[3/3] bundle SSR handler + deps into the render function"
npx esbuild vercel-entry.ts --bundle --platform=node --format=cjs --outfile=.vercel/output/functions/render.func/index.cjs 2>&1

cat > .vercel/output/functions/render.func/.vc-config.json <<'JSON'
{ "runtime": "nodejs22.x", "handler": "index.cjs", "launcherType": "Nodejs", "supportsResponseStreaming": true }
JSON
cat > .vercel/output/config.json <<'JSON'
{ "version": 3, "routes": [ { "handle": "filesystem" }, { "src": "/(.*)", "dest": "/render" } ] }
JSON

echo "done -> .vercel/output ready for: bunx vercel deploy --prebuilt"
